package com.csumb.cst363;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;

import java.sql.*;
import java.util.regex.Pattern;

import static java.sql.Types.NULL;


@Controller
public class ControllerPrescriptionCreate {
	private final Pattern pattern = Pattern.compile("[^a-zA-Z\s\\d]");//pattern a-z
	@Autowired
	private JdbcTemplate jdbcTemplate;

	/**
	 * Doctor requests blank form for new prescription.
	 */
	@GetMapping("/prescription/new")
	public String newPrescripton(Model model) {
	   //add new prescription obj from html
		model.addAttribute("prescription", new Prescription());
		return "prescription_create";//html page
	}

	/**
	 * Process the new prescription form.
	 * 1. Validate that Doctor SSN exists and matches Doctor Name.
	 * 2. Validate that Patient SSN exists and matches Patient Name.
	 * 3. Validate that Drug name exists.
	 * 4. Insert new prescription.
	 * 5. If error, return error message and the prescription form
	 * 6. Otherwise, return the prescription with the rxid number that was generated by the database.
	 */
	@PostMapping("/prescription")
	public String newPrescription(Prescription p, Model model) {
		try (Connection con = getConnection()) {
			checkInput(p);//call function to validate user input
			
			//Checking for a legal refill quantity throw error if over 15
			if (p.getQuantity() > 15 || p.getQuantity() < 1) throw new SQLException("Wrong Quantity, should be 15 or less");
			
			//initialize variables
			int dr_id, pat_id, drug_id, detail_id;
			
			//Check Doctor details are correct first get doctor by id 1-3 in order from sql table fields
			PreparedStatement ps = con.prepareStatement("select id from Doctor where last_name=? and first_name=? and ssn=?");
			String first = p.getDoctorFirstName();//initialize first variable
			first = first.substring(0, 1).toUpperCase() + first.substring(1).toLowerCase();//Crystal
			p.setDoctorFirstName(first);
			p.setDoctorLastName(p.getDoctorLastName().toUpperCase());//LAST NAME
			ps.setString(1, p.getDoctorLastName());
			ps.setString(2, p.getDoctorFirstName());
			ps.setString(3, p.getDoctor_ssn());
			ResultSet rs = ps.executeQuery();
			
			//check If doctor is found is saved if not warn
			if (rs.next()) dr_id = rs.getInt(1);//primary key from sql Doctor.id
			else throw new SQLException("Doctor not found");
			
			//Check patient details are correct 1-3 in order from sql table fields
			ps = con.prepareStatement("select id from Patient where first_name=? and last_name=? and ssn=?");
			first = p.getPatientFirstName();//initialize first variable
			first = first.substring(0, 1).toUpperCase() + first.substring(1).toLowerCase();//Crystal
			p.setPatientFirstName(first);
			p.setPatientLastName(p.getPatientLastName().toUpperCase());//LAST NAME
			ps.setString(1, p.getPatientFirstName());
			ps.setString(2, p.getPatientLastName());
			ps.setString(3, p.getPatient_ssn());
			rs = ps.executeQuery();
			
			//check If patient found save patient id then warn
			if (rs.next()) pat_id = rs.getInt(1);//primary key sql Patient.id
			else throw new SQLException("Patient not found");

			//Check drug details are correct by getting drug 1 for sql table field name
			ps = con.prepareStatement("select id,name from Drug where name=?");
			first = p.getDrugName();//initialize first variable
			first = first.substring(0, 1).toUpperCase() + first.substring(1).toLowerCase();//Advil
			p.setDrugName(first);
			ps.setString(1, p.getDrugName());
			rs = ps.executeQuery();
			
			//check If drug found drug id is saved then warn
			if (rs.next()) drug_id = rs.getInt(1);//primary key sql Drug.id
			else throw new SQLException("Medicine not found");

			//adding prescription with details 1,2,4 from sql table fields
			ps = con.prepareStatement("insert into Prescription(doctor_id, patient_id, pdetail_id, drug_id) values(?, ?,?,?)",
			      Statement.RETURN_GENERATED_KEYS);
			ps.setInt(1, dr_id);
			ps.setInt(2, pat_id);
			ps.setInt(4, drug_id);

			//adding prescription's details 1-4 from sql table fields
			PreparedStatement ps2 = con.prepareStatement("insert into Prescription_detail(issued_date, quantity, pharmacy_id, last_fill_date ) "
			      + "values(?,?,?,?)",
				Statement.RETURN_GENERATED_KEYS);
			ps2.setDate(1, new Date(System.currentTimeMillis()));//in milliseconds
			ps2.setInt(2, p.getQuantity());
			ps2.setNull(3, NULL);
			ps2.setNull(4, NULL);
			ps2.executeUpdate();
			
			//retrieve keys from ps2 Prescription_details sql table
			rs = ps2.getGeneratedKeys();
			rs.next();
			detail_id = rs.getInt(1);//get primary key sql Prescription_detail.id
			ps.setInt(3, detail_id);
			ps.executeUpdate();
			
			rs = ps.getGeneratedKeys();//get keys for RX no
			rs.next();
			p.setRxid(rs.getInt(1));//get primary key sql Prescription.rx
			
			model.addAttribute("message", "Prescription created.");//text from html
			model.addAttribute("prescription", p);//obj from html
			return "prescription_show";//html page
		} 
		catch (SQLException e) {//error
			model.addAttribute("message", e.getMessage());//text from html
			model.addAttribute("prescription", p);//obj from html
			return "prescription_create";//html page
		}
	}//end of newPrescription function

	/**
	 * return JDBC Connection using jdbcTemplate in Spring Server
	 * java database connection
	 */
	private Connection getConnection() throws SQLException {
		return jdbcTemplate.getDataSource().getConnection();
	}
	
   /*private function verify correct user input invalid if character error input or no user input for doctor*/
	private void checkInput(Prescription p) throws SQLException {
		if (pattern.matcher(p.getDoctorFirstName()).find() ||
			    pattern.matcher(p.getDoctorLastName()).find() ||
			    pattern.matcher(p.getDoctor_ssn()).find() ||
			    pattern.matcher(p.getPatient_ssn()).find() ||
			    pattern.matcher(p.getPatientFirstName()).find() ||
			    pattern.matcher(p.getPatientLastName()).find() ||
			    pattern.matcher(p.getDrugName()).find()) {
			throw new SQLException("Illegal characters in form");
		} 
		else if (p.getDoctorFirstName().isBlank() || p.getDoctorLastName().isBlank() ||
			           p.getDoctor_ssn().isBlank() || p.getPatient_ssn().isBlank() ||
			           p.getPatientFirstName().isBlank() || p.getPatientLastName().isBlank()
			           || p.getDrugName().isBlank()) {
			throw new SQLException("Missing fields in form");
		}
	}//end of checkInput
	
}//end of class