package com.csumb.cst363;

/**
 * This class is used to transfer data to/from patient templates.
 */
public class Patient {
   //attributes
	private String patientID;  // unique id generated by database.
	private String last_name;
	private String first_name;
	private String birthdate;  // yyyy-mm-dd
	private String ssn;
	private int addressID;
	private String street;
	private String unitNo;
	private String city;
	private String state;
	private String zipcode;
	//fields are data about primary doctor
	private int primaryID;
	private String primaryName;

	//getters and setters
	public String getPatientID() {
		return patientID;
	}

	public void setPatientID(String patientID) {
		this.patientID = patientID;
	}

	public String getLast_name() {
		return last_name;
	}

	public void setLast_name(String last_name) {
		this.last_name = last_name;
	}

	public String getFirst_name() {
		return first_name;
	}

	public void setFirst_name(String first_name) {
		this.first_name = first_name;
	}

	public String getBirthdate() {
		return birthdate;
	}

	public void setBirthdate(String birthdate) {
		this.birthdate = birthdate;
	}

	public String getSsn() {
		return ssn;
	}

	public void setSsn(String ssn) {
		this.ssn = ssn;
	}

	public int getAddressID() {
		return addressID;
	}

	public void setAddressID(int addressID) {
		this.addressID = addressID;
	}

	public int getPrimaryID() {
		return primaryID;
	}

	public void setPrimaryID(int primaryID) {
		this.primaryID = primaryID;
	}

	public String getPrimaryName() {
		return primaryName;
	}

	public void setPrimaryName(String primaryName) {
		this.primaryName = primaryName;
	}

	public String getStreet() {
		return street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getUnitNo() {
		return unitNo;
	}

	public void setUnitNo(String unitNo) {
		this.unitNo = unitNo;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZipcode() {
		return zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	//stringifier
	@Override
	public String toString() {
		return "Patient{" +
			       "patientID='" + patientID + '\'' +
			       ", last_name='" + last_name + '\'' +
			       ", first_name='" + first_name + '\'' +
			       ", birthdate='" + birthdate + '\'' +
			       ", ssn='" + ssn + '\'' +
			       ", addressID=" + addressID +
			       ", street='" + street + '\'' +
			       ", unitNo='" + unitNo + '\'' +
			       ", city='" + city + '\'' +
			       ", state='" + state + '\'' +
			       ", zipcode='" + zipcode + '\'' +
			       ", primaryID=" + primaryID +
			       ", primaryName='" + primaryName + '\'' +
			       '}';
	}
}